name: Run script on push to develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install LaTeX (texlive-full)
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Download and install fonts
        run: |
          wget http://www.hayeren.am/fonts/GHEAMariam.zip -O /tmp/GHEAMariam.zip
          unzip /tmp/GHEAMariam.zip -d /tmp/GHEAMariam
          sudo mkdir -p /usr/local/share/fonts/GHEAMariam
          sudo cp /tmp/GHEAMariam/*.otf /usr/local/share/fonts/GHEAMariam/
          sudo fc-cache -fv

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run build script
        run: |
          python build.py
          python build.py

      - name: Move and rename main.pdf
        run: |
          mv out/main.pdf MasterThesis.pdf

      - name: Keep only main.pdf, remove other files
        run: |
          find . -mindepth 1 -not -path './.git/*' -not -name '.git*' -not -path './MasterThesis.pdf' -delete
          find . -type d -empty -not -path './.git' -delete

      - name: Commit and push changes to develop branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b pdf
          git add .
          git commit -m "Automated build result"
          git push -u origin pdf --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
